[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://be.linkedin.com/in/haroldpreyers"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/hpreyers"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/hpreyers"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/hpreyers"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/haroldpreyers"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"